/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1jHu4WZZ5uuHXzhD34Sz7C

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_5BvWIcnITpj3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 5bvWIcnITpj3/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_5BvWIcnITpj3
});
